# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Site settings
title: KBCOM 2018
description: 1st Workshop on Knowledge Base Construction, Reasoning and Mining

# add google analytics if desired (and uncomment in _includes/head.html)
google_analytics: UA-34679733-3

# Build settings
markdown: kramdown

# Notes: 
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
